- name: Request certificate
  shell: >
    {{ certbot_certonly_command }} --webroot --webroot-path {{ item.webroot_path }}{% for domain in item.domains %} -d {{ domain }}{% endfor %}
  tags:
    - certbot
